sudo: required
services:
  - docker
before_install:
  - docker build -t devops/adv .
#  - docker login -u $DOCKER_USER -p $DOCKER_PASS
#  - docker push devops/adv:latest
  echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker push crycrime/devops_adv
