notifications:
  email: false
sudo: required
language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules

services:
  - docker

script:
  - docker build -t devops_adv:latest .
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
